//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.15
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 939c7581-479a-4d1b-850f-bcdad3898935 aws-my-sample-app-android-v0.15";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
            Regions.US_WEST_2;

    // Top right of support center
    public static final String AMAZON_ACCT_ID =
            "208475174974";

    // Found through cognito federated activities
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
            "us-west-2:9e03d010-e65d-4c51-b69a-094dab3f412f";


    // Found through cognito user pools
    public static final String AMAZON_COGNITO_USER_POOL_ID =
                "us-west-2_USuyIqxz4";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
            "1ial28m774tnicuhmoh8m76hs5";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
            "er4esj76o8i1dquc4jmqiq9ippqoth9rvr86mjug39cstc1jrat";
    public static final String AMAZON_COGNITO_AUTH_ID =
            "arn:aws:iam::208475174974:role/Cognito_Shotgun_New_Identity_User_PoolAuth_Role";
    public static final String AMAZON_COGNITO_UNAUTH_ID =
            "arn:aws:iam::208475174974:role/Cognito_Shotgun_New_Identity_User_PoolUnauth_Role";
}
