//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.15
//
package com.g13.shotgun.userpools;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.View;

import com.amazonaws.mobile.user.signin.CognitoUserPoolsSignInProvider;
import com.g13.shotgun.util.ViewHelper;
import com.g13.shotgun.R;

/**
 * Activity to prompt for account sign up information.
 */
public class SignUpActivity extends Activity {
    /** Log tag. */
    private static final String LOG_TAG = SignUpActivity.class.getSimpleName();

    @Override
    protected void onCreate(final Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sign_up);
    }

    /**
     * Retrieve input and return to caller.
     * @param view the Android View
     */
    public void signUp(final View view) {
        final String username = ViewHelper.getStringValue(this, R.id.signup_username);
        final String password = ViewHelper.getStringValue(this, R.id.signup_password);
        final String firstName = ViewHelper.getStringValue(this, R.id.signup_first_name);
        final String lastName = ViewHelper.getStringValue(this, R.id.signup_last_name);
        final String gender = ViewHelper.getStringValue(this, R.id.signup_gender);
        final String email = ViewHelper.getStringValue(this, R.id.signup_email);
        final String phone = ViewHelper.getStringValue(this, R.id.signup_phone);

        Log.d(LOG_TAG, "username = " + username);
        Log.d(LOG_TAG, "firstname = " + firstName);
        Log.d(LOG_TAG, "lastname = " + lastName);
        Log.d(LOG_TAG, "gender = " + gender);
        Log.d(LOG_TAG, "email = " + email);
        Log.d(LOG_TAG, "phone = " + phone);

        final Intent intent = new Intent();
        intent.putExtra(CognitoUserPoolsSignInProvider.AttributeKeys.USERNAME, username);
        intent.putExtra(CognitoUserPoolsSignInProvider.AttributeKeys.PASSWORD, password);
        intent.putExtra(CognitoUserPoolsSignInProvider.AttributeKeys.GIVEN_NAME, firstName);
        intent.putExtra(CognitoUserPoolsSignInProvider.AttributeKeys.FAMILY_NAME, lastName);
        intent.putExtra(CognitoUserPoolsSignInProvider.AttributeKeys.GENDER, gender);
        intent.putExtra(CognitoUserPoolsSignInProvider.AttributeKeys.EMAIL_ADDRESS, email);
        intent.putExtra(CognitoUserPoolsSignInProvider.AttributeKeys.PHONE_NUMBER, phone);


        setResult(RESULT_OK, intent);

        finish();
    }
}
